### ISSUE TITLE
SetupTools Version Conflict

### ISSUE THREAD

**Issue by anuragjain67** [hashedin/django-project-template#14]
When new django project created from this template, and we run `python bootstrap.py` then following error comes

```
Traceback (most recent call last):
  File "bootstrap.py", line 159, in <module>
    ws.require(requirement)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (setuptools 3.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('setuptools>=8.0'))
```

It seems we don't have version defined  in buildout. 

Solution I am following : 

```
* sudo rm -rf /usr/local/lib/python2.7/dist-packages/setuptools
Or 
* pip install setuptools --upgrade 
```

Whats the better solution ?

**Comment by sidharthchh** [comment]
http://reinout.vanrees.org/weblog/2013/07/08/new-setuptools-buildout.html
